// Glosario único de métricas. El frontend renderiza un ícono ⓘ junto a
// cada métrica y muestra el tooltip con: qué es, qué valor es bueno/malo,
// qué hacer. Centralizado acá para que admin pueda editar redacción
// sin tocar el frontend.

const ADS = {
  spend:         { label: 'Gasto', short: '€',
                   what: 'El dinero invertido en el período.',
                   good_bad: '',
                   action: '' },
  impressions:   { label: 'Impresiones',
                   what: 'Cuántas veces se mostró el anuncio (cuenta repeticiones a la misma persona).',
                   good_bad: 'No medí éxito por impresiones solas — siempre mirar junto a alcance y clics.',
                   action: '' },
  reach:         { label: 'Alcance',
                   what: 'Cuántas personas distintas vieron el anuncio (sin repetir).',
                   good_bad: 'Más alcance con poco presupuesto = la creative funciona y enganchó al algoritmo.',
                   action: '' },
  frequency:     { label: 'Frecuencia',
                   what: 'Promedio de veces que cada persona vio el anuncio (Impresiones ÷ Alcance).',
                   good_bad: '👍 entre 1,2 y 3 · 👎 >3,5 (la gente se satura, conviene rotar creatives).',
                   action: 'Frecuencia alta = rotar creative o ampliar audiencia.' },
  clicks:        { label: 'Clics',
                   what: 'Cantidad de veces que hicieron clic en el anuncio.',
                   good_bad: '',
                   action: '' },
  ctr:           { label: 'CTR',
                   what: 'Click-Through Rate: % de los que vieron el anuncio e hicieron clic (Clics ÷ Impresiones).',
                   good_bad: '👍 >1% · 🔵 0,5–1% aceptable · 👎 <0,5% no engancha.',
                   action: 'CTR bajo = revisar el copy/imagen, segmentación o objetivo.' },
  cpc:           { label: 'CPC',
                   what: 'Costo por Clic: cuánto pagás por cada clic (Gasto ÷ Clics).',
                   good_bad: '👍 <€0,15 (campañas de tráfico) · 👎 >€0,40.',
                   action: 'CPC alto + CTR bajo = mala combinación. Pausar o cambiar creative.' },
  cpm:           { label: 'CPM',
                   what: 'Costo por Mil impresiones: lo que pagás por mostrar el anuncio 1.000 veces.',
                   good_bad: 'Comparativo: mientras más bajo, más barato es llegar a la gente. Varía por sector.',
                   action: '' },
  results:       { label: 'Resultados',
                   what: 'Las acciones que buscás (mensajes, compras, visitas). Lo que más importa.',
                   good_bad: 'Es la métrica de verdad — gasto sin resultados = gasto malgastado.',
                   action: '' },
  cpa:           { label: 'Costo por Resultado',
                   what: 'CPA: cuánto te cuesta cada resultado (Gasto ÷ Resultados).',
                   good_bad: 'Más bajo = mejor. Comparalo contra tu margen — si CPA > margen, perdés plata.',
                   action: '' },
  roas:          { label: 'ROAS',
                   what: 'Return on Ad Spend: euros de venta por cada euro gastado.',
                   good_bad: '👍 >1 ganás · 👎 <1 perdés. Solo aplica si hay tracking de compra.',
                   action: '' },
};

const IG = {
  followers:     { label: 'Seguidores',
                   what: 'Cuánta gente te sigue.',
                   good_bad: 'Lo importante es el crecimiento, no el número absoluto.',
                   action: '' },
  reach:         { label: 'Alcance',
                   what: 'Personas distintas que vieron tu contenido en el período.',
                   good_bad: 'Si crece sin postear más = el algoritmo te está empujando.',
                   action: '' },
  views:         { label: 'Visualizaciones',
                   what: 'Veces que se mostró tu contenido (incluye repeticiones).',
                   good_bad: 'Vistas altas con poca interacción = scroll pasivo, conviene mejorar el gancho inicial.',
                   action: '' },
  profile_views: { label: 'Visitas al perfil',
                   what: 'Cuántas veces entraron a tu perfil.',
                   good_bad: 'Visita al perfil = interés real. Asegurate de tener bio + link claros.',
                   action: '' },
  website_clicks:{ label: 'Clics al sitio',
                   what: 'Cuántos clickearon el link de tu bio.',
                   good_bad: '',
                   action: '' },
  interactions:  { label: 'Interacciones',
                   what: 'Suma de likes + comentarios + guardados + compartidos.',
                   good_bad: '',
                   action: '' },
  engagement_rate:{ label: 'Tasa de interacción',
                   what: 'Interacciones ÷ alcance.',
                   good_bad: '👍 >5% · 🔵 2–5% normal · 👎 <2%. Cuanto más alto, más conecta tu contenido.',
                   action: '' },
  likes:         { label: 'Likes',
                   what: 'Personas que dieron like.',
                   good_bad: 'Métrica de superficie — no decide el algoritmo.',
                   action: '' },
  comments:      { label: 'Comentarios',
                   what: 'Cuánta gente comentó.',
                   good_bad: 'Comentarios largos pesan más que cortos para el algoritmo.',
                   action: '' },
  saved:         { label: 'Guardados',
                   what: 'Cuánta gente lo guardó para volver después.',
                   good_bad: '⭐ Señal MUY fuerte de interés real. Si un post tiene muchos guardados, escalalo en ads.',
                   action: 'Identificá qué publicaciones tienen más guardados y replicá el patrón.' },
  shares:        { label: 'Compartidos',
                   what: 'Cuánta gente lo compartió.',
                   good_bad: '⭐ Amplifica alcance gratis. Igual de importante que los guardados.',
                   action: '' },
  plays:         { label: 'Reproducciones (Reel)',
                   what: 'Veces que se reprodujo el reel.',
                   good_bad: '',
                   action: '' },
};

function get(kind, metric) {
  const map = kind === 'ig' ? IG : ADS;
  return map[metric] || null;
}
function all() { return { ads: ADS, ig: IG }; }

module.exports = { get, all, ADS, IG };
